### ISSUE TITLE
Segmentation fault when loading any plugin on Linux arm64

### ISSUE THREAD

**Issue by EliaCereda** [CoppeliaRobotics/v_repClientApplication#1]
When trying to get the simulator to run under Linux arm64, we found that the application would crash with a segmentation fault during startup as soon as any plugin was loaded.

The problem appears to be caused by the `loadSimLibrary` and `getSimProcAddresses` functions from `simLib.h`:
https://github.com/CoppeliaRobotics/include/blob/5127ddba272114975290f015617085ffc09a978b/simLib.h#L27

Both the client application and the plugins will have copies of these functions, which differ due to the client being compiled with `QT_FRAMEWORK` defined, while it's not on most plugins.

Since the C++ mangled names generated by GCC do not consider the return type of a function (https://stackoverflow.com/a/40794371/1821284), the mangled name for `loadSimLibrary` will be the same regardless of `QT_FRAMEWORK`, while the mangled name for `getSimProcAddresses` changes.

You can see the resulting symbols in the client executable and one example plugin below:

```shell
$ readelf -Ws coppeliaSim | grep -E 'loadSimLibrary|getSimProcAddresses'
   151: 0000000000002ac0   940 FUNC    GLOBAL  DEFAULT   13 _Z14loadSimLibraryPKc
   517: 0000000000003074 39720 FUNC    GLOBAL  DEFAULT   13 _Z19getSimProcAddressesP8QLibrary
[...]
```

```shell
$ readelf -Ws libsimExtCodeEditor.so | grep -E 'loadSimLibrary|getSimProcAddresses'
   745: 00000000000370c0    96 FUNC    GLOBAL DEFAULT   11 _Z14loadSimLibraryPKc
[...]
  1837: 0000000000037170 50792 FUNC    GLOBAL DEFAULT   11 _Z19getSimProcAddressesPv
[...]
```

When a plugin is loaded, its initialization code will call the two functions one after the other. For `loadSimLibrary`, since the client already defines a symbol named `_Z14loadSimLibraryPKc`, it will get picked up by the dynamic linker over the copy inside the plugin. For `getSimProcAddresses` instead, the mangled names differ, so the plugin will correctly invoke its own copy of the function. This mismatch causes a `QLibrary` object to be passed to the non-QT version of `getSimProcAddresses`, resulting in the segmentation fault.

**Note:** a similar issue also exists between plugins, in which every plugin will call `loadSimLibrary` and `getSimProcAddresses` of the first plugin that was loaded instead of its own. This does not result in visible problems as long as they all have identical implementations, but it should probably be avoided.

It's not clear to me how this does not cause a problem in the official builds of Coppelia for x86_64. I have opened a PR with the fix that we applied to get over this problem with our students, but it might also be that we are making mistakes elsewhere in the build process that result in this problem.

**Comment by fferri** [comment]
Thanks for reporting this!

Do you have a backtrace of the crash? Was the crash happening somewhere in `dlsym()`?

I noticed a perhaps similar issue on Linux, when building with cmake (as you may have noticed, some items such as coppeliaSimClientApplication and coppeliaSimLib still have a qmake project file, and a CMake file) where I see a crash originating from `dlsym()` when loading any plugin.

**Comment by EliaCereda** [comment]
I don't have the backtrace on hand, but it was definitely inside `dlsym` called by libsimExtCodeEditor.so's copy of `getSimProcAddresses` (or any other non-QT plugin). I also confirm that we are building with cmake.

It's good to hear that this is something that you already encountered, because it didn't seem to be arm64 specific.

In general, it would be awesome if you could provide more detailed instructions on how you compile Coppelia from source. We followed the instructions from https://www.coppeliarobotics.com/helpFiles/en/compilingCoppeliaSim.htm, but that does not explain the specific commands to build each subproject (e.g., cmake vs qmake). It would also be great to be able to compile everything from scratch without having to rely on an existing installation directory.
